Added moving average filter
Alek050/databallpy pull request #108
Opened 2023-07-05 13:35 UTC by DaanGro

We have to discuss wether to implement this in get_match() or leave it to the user.
Also for different filters, poetry has issues regarding adding scipy (clashes with our current Python versions), we have to discuss how to handle this.

2023-07-05 14:42 UTC, DaanGro commented
Added scipy, and savitzky golay filter

2023-07-10 07:18 UTC, Alek050 requested changes

2023-07-10 07:18 UTC, Alek050 commented on databallpy/filters.py
> +    """Function to filter specified columns, available filters are: moving average
Add savgol_filter

2023-07-10 07:18 UTC, Alek050 commented on databallpy/filters.py
> +    kind: str,
Maybe refactor this to `filter_type` or something. I think `kind` is not specific enough.

2023-07-10 07:19 UTC, Alek050 commented
> We have to discuss wether to implement this in get_match() or leave it to the user. Also for different filters, poetry has issues regarding adding scipy (clashes with our current Python versions), we have to discuss how to handle this.

I think we have to leave this to users for most of the part. The package needs to be able to read in all data and support features, but it is up to the user how data is preprocessed and features are calculated.

2023-08-07 09:14 UTC, Alek050 approved these changes

2023-08-07 09:14 UTC, merged