fix(synchronise_tracking_and_event_data): fix check for missing playe…
Alek050/databallpy pull request #79
Opened 2023-05-11 15:37 UTC by rdghe

closes #78

2023-05-11 15:39 UTC, rdghe commented
Maybe worth considering making `-999` a global variable for missing data defined somewhere, as currently it's "hardcoded" in a bunch of places. But that's out of the scope of the issue at hand.

2023-05-13 07:31 UTC, Alek050 requested changes
Thanks for pointing this out. Make sure to also add a test for this so we are certain that this will not be changed in future refactors.

2023-05-14 14:14 UTC, rdghe commented
Tests added @Alek050

2023-05-15 13:24 UTC, rdghe commented on tests/utils/test_synchronise_tracking_and_event_data.py
> +        event_data.loc[2, "player_id"] = -999
++

2023-05-15 13:25 UTC, rdghe commented on tests/utils/test_synchronise_tracking_and_event_data.py
>          event_data = self.match_to_sync.event_data
Done, but I suppose it makes sense to have this everywhere `event_data` or `tracking_data` is accessed from `self.match_to_sync`, so I did that. Let me know if I am wrong

2023-05-15 13:26 UTC, rdghe commented on databallpy/utils/synchronise_tracking_and_event_data.py
> +        if not np.isnan(event["player_id"]) and event["player_id"] != -999:
++

2023-05-18 08:51 UTC, Alek050 approved these changes

2023-05-18 08:51 UTC, merged